#!/bin/bash -x

IMAGE=jdonato1/tensorflow-from-source
CONTAINER=tf_for_old_intel
TAG=bionic

docker rm -f $CONTAINER ; \
	docker build --rm=${RM:-false} -t $IMAGE:latest -t $IMAGE:$TAG . && \
	docker run \
		--name $CONTAINER \
		-it \
		$IMAGE "$@"

