#!/bin/bash
# Tensorflow builder
# Jorge Donato / jdonato1@sbcglobal.net

echo "NOTE: about 12,000 objects to compile, prepare for 8 hour compile"
printf "Press Enter to continue (^C to abort): "
read WAIT_FOR_ENTER

apt-get update
apt-get upgrade -y
apt-get install -y         openjdk-8-jdk         curl 	gnupg2 	git

echo "deb [arch=amd64] http://storage.googleapis.com/bazel-apt stable jdk1.8" | tee /etc/apt/sources.list.d/bazel.list 
curl https://bazel.build/bazel-release.pub.gpg | apt-key add - || exit 10

apt-get update &&         apt-get install -y                 python3                 python3-dev 		python3-numpy 		python3-pip                 gcc                 g++                 bazel

rm /usr/bin/python
ln -s /usr/bin/python3 /usr/bin/python
rm /usr/bin/pip
ln -s /usr/bin/pip3 /usr/bin/pip

cd /root
rm -rf tensorflow
git clone https://github.com/tensorflow/tensorflow.git --branch master --single-branch && \
        cd tensorflow && \
        ( echo /usr/bin/python3 ) | ./configure && \
	cd /root/tensorflow && \
        bazel build --config=monolithic //tensorflow/tools/pip_package:build_pip_package && \
        bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg && \
        mv /tmp/tensorflow_pkg/tensorflow-*.whl . && \
        ls -l tensorflow-*.whl && \
        echo && \
        echo "To install this tensorflow onto a computer with an existing package (as root):" && \
        echo "#   pip3 install --upgrade " tensorflow-*whl && \
        echo && \
        echo Done Mon Oct 22 21:56:33 UTC 2018
